language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: zhangyiant@hotmail.com
  on:
    tags: true
  api_key:
    secure: aPeG6Z9tu+TwYMGVSNpozOLJB2tRXm8/WJ3OeKSwdzSYn/H4gfbTqAVFFNZVxgtKaPP7lBnIcarxxiUs1xl0qDxVEDEt5W6VodBcQWfF8vG6qOOFZYf9y8l08B7hsRFV2HL2QMuJfP1lKN5sw+A9GO6bv9KFgF6JooyP/g+qiXiuN/g5OrfUyNHTrlXqL160KTHq20HG2H3F9YsvM4zdlCqReQL6jinYfypVIWtRwjkCbduh5kWGMT80zLd5enCwPAuCi440fS6jBCcTw6nJVxpS/gdVBk+Jfm1nDCM00aYIYjHAt7EHTziTPCEJb5kb4qrj61tJn8w5HHKCOp48h9tulbaCgufktTk9mmg3eYVsKj7N2Y93gStteLn1+cbImG0I67P7J4g5mQrAdzWSUnO50DYULFJWhC1pXfkX7NkuIzMTfmDIhfDCNEGgUIYPfVPKFGB5WiR4fFD/HmMNFW+1lAGpL2Pqf3EMvXauvZp+9Exax8xZnJJ4ZMidE2qShCYcaTTfjUn8RoG5c4AsDBbGRQAKyBZgt5Uwefvu7iZKEXk5gpGnHn/XWZYySD5mxzRnd+uXiOQk4A/Ck9Fb8Ap8QQMOOqeWEggZfBW9l4AOXligkkrFGXd7UYjdUTC4LoPUGhRu9mbcvJRfM5usxR1T86ZGnQvn4fo9OD8pZFM=
