language: node_js
node_js:
- lts/*
deploy:
  provider: npm
  email: zhangyiant@hotmail.com
  on:
    tags: true
  api_key:
    secure: HojGHk9rly5O71LrS1IACk9l5qY/XvtNV1UVILJbzyw6aNPOC8IDiO558qr+QAm91usWgPpa7uJVNfK43I7qiuqMMesxA9Bneehcj3vxWlGnV3VSY9UjDNg1r4MAmZ/NLbn6ZfVZuJ8lBftZS8rXTfTLuyP7rtJd2xV3U+D760CSJtzpZGFLKZz4Od9tIqoKr3t6FbrqTNhH7pQ9OollzPjhp9ImKPW2SNrE1alKerFw5pTFZkFNzbUqJGDRENH7lIfIC0TtoGe1d539KXTfL7NhukM90VnAayoYoyaRmCT8r5ernPH9Q/gJH4nCo207VX29E/EBipu4gleZTZ3gwN1Ctjakc70Nl1cJn43WJRX9zbG/Q/EHXeWJVRtsCQ2dokg+eNWLP7qsmc2nCpvlv0gUKAG95Hu5UJc7QxcMTRkJsagN9DGpJkVBBTSPp7wTPGV15G41y/of/Q4wgXT1x4JIT5WR1lnEfW350u1ml6+ot11jPLA+6poiZFX5a1FguaNU9Qwq9TIwj5y0WZ0SZrt4AU3tIicadb9wQ6xfflWsBpuTSl7k/3Z8t0wP1qHbXXAaIp8vYQinpbX5veMPEkg3gcgMW8qGKMmJGmKAdx1UckC8/nKcQ5ycPyWw2sPNy17vzotc2BIyRyLsyVSkeV5v7muNxbONodH7eDCalz8=
